# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# compile CXX with /usr/bin/c++
CXX_FLAGS = -I/home/ubuntu/opencv-3.1.0/include/opencv -I/home/ubuntu/opencv-3.1.0/include   

CXX_DEFINES = 

